### ISSUE TITLE
lambda cold start?

### ISSUE THREAD

**Issue by ddddave** [yai333/AppsyncServerlessCMS#2]
Hi, thanks for sharing this project. I’ve worked with lambda in a VPC in the past and I’d like to know if you’re experiencing the 10s lambda cold start times with this setup. I haven’t used serverless aurora yet so not sure if this is solved with that type of RDS deployment. Thanks

**Comment by yai333** [comment]
hi mate, code start should n't take 10s that long time.  you could warm up the lambda by using this plugin https://github.com/FidelLimited/serverless-plugin-warmup
